set pad_wire_necking on
bus diagonal
fanout 15
route 15
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
route 15 16
clean 10
filter 10
recorner diagonal
status_file
